-- Update host profile to host role
UPDATE profiles 
SET user_role = 'host', 
    business_name = 'EASYHALL Premium Venues',
    full_name = 'Fares Abdelbasset BOUDRA'
WHERE id = 'edc892af-b631-46e5-92e2-933efb65f0af';

-- Insert Wedding Hall venues (10)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Palais El Feth', 'Découvrez l''élégance intemporelle du Palais El Feth, un joyau architectural niché au cœur d''Alger. Notre salle de réception peut accueillir jusqu''à 800 invités dans un cadre somptueux orné de lustres en cristal, de colonnes majestueuses et de finitions dorées. Nous proposons un service traiteur raffiné, une sonorisation professionnelle et une équipe dédiée pour faire de votre mariage un événement inoubliable. Les jardins paysagers offrent un cadre idyllique pour vos photos.', 'Algiers', 'Boulevard Mohamed V, El Biar, Alger', 'Wedding Hall', 800, 350000, 45000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Salle des Fêtes El Baya', 'La Salle des Fêtes El Baya incarne le raffinement oranais dans toute sa splendeur. Avec une capacité de 500 personnes, cet espace élégant combine traditions algériennes et modernité européenne. Les hauts plafonds, les tapis persans et l''éclairage tamisé créent une atmosphère romantique parfaite. Notre chef cuisinier prépare des mets exquis mêlant saveurs méditerranéennes et orientales. Parking privé sécurisé disponible.', 'Oran', 'Rue Larbi Ben M''hidi, Centre-ville, Oran', 'Wedding Hall', 500, 280000, 35000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Le Diamant Bleu', 'Le Diamant Bleu de Constantine vous offre une expérience unique surplombant les gorges du Rhumel. Cette salle prestigieuse de 600 places marie architecture ottomane et équipements modernes. Les baies vitrées panoramiques offrent une vue spectaculaire sur la ville des ponts. Service VIP, décoration florale personnalisée et suite nuptiale inclus. Un lieu magique où vos rêves deviennent réalité.', 'Constantine', 'Boulevard Zighoud Youcef, Sidi Mabrouk, Constantine', 'Wedding Hall', 600, 300000, 38000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Riad El Andalous', 'Le Riad El Andalous de Tlemcen vous transporte dans l''Andalousie mauresque. Cette demeure historique restaurée accueille 400 convives dans un décor de zellige, fontaines et jardins intérieurs. L''authenticité des lieux, les arcades sculptées et les patios ombragés créent une ambiance enchanteresse. Idéal pour les cérémonies traditionnelles avec henné et musique andalouse.', 'Tlemcen', 'Rue des Almohades, Quartier Historique, Tlemcen', 'Wedding Hall', 400, 250000, 32000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Jardin d''Orient', 'Le Jardin d''Orient à Annaba allie nature et élégance pour vos célébrations. Niché dans un parc de 2 hectares, cet espace peut recevoir 450 invités sous des tonnelles fleuries ou dans notre salle climatisée. La brise marine, les palmiers centenaires et l''éclairage féerique nocturne créent une atmosphère paradisiaque. Service traiteur fruits de mer et spécialités annabies disponible.', 'Annaba', 'Route de la Corniche, Cap de Garde, Annaba', 'Wedding Hall', 450, 220000, 28000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Royal Palace', 'Le Royal Palace de Sétif représente le summum du luxe dans les Hautes Plaines. Sa salle de 550 places impressionne par ses colonnes de marbre, ses fresques murales et son système son Dolby Surround. La décoration changeante selon les saisons et l''espace cocktail séparé en font un lieu versatile. Équipe de wedding planners professionnels à votre service.', 'Setif', 'Avenue du 8 Mai 1945, Cité El Hidhab, Setif', 'Wedding Hall', 550, 270000, 34000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'La Perle de Kabylie', 'Au cœur des montagnes de Kabylie, La Perle offre un cadre authentique pour 350 invités. Architecture berbère traditionnelle avec toits de tuiles rouges, poutres apparentes et terrasses panoramiques sur le Djurdjura. Cuisine kabyle raffinée avec couscous royal et méchoui. Hébergement sur place dans nos chalets montagnards. Une expérience culturelle unique.', 'Tizi Ouzou', 'Village Ait Boumahdi, Route de Tikjda, Tizi Ouzou', 'Wedding Hall', 350, 200000, 25000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Château des Étoiles', 'Le Château des Étoiles à Blida évoque les grandes demeures coloniales de la Mitidja. Entouré d''orangeraies parfumées, ce domaine de 700 places possède des salons privés, une chapelle et un parc romantique. L''escalier monumental en fer forgé et les lustres vénitiens créent un décor de conte de fées. Feux d''artifice et lâcher de colombes sur demande.', 'Blida', 'Route des Orangers, Beni Mered, Blida', 'Wedding Hall', 700, 320000, 40000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Les Jardins de Sidi Fredj', 'Face à la Méditerranée, Les Jardins de Sidi Fredj offrent un cadre exceptionnel pour 900 invités. Cet ancien complexe touristique rénové combine architecture mauresque et vue mer imprenable. Plusieurs espaces modulables : plage privée, jardins tropicaux et grande salle climatisée. Idéal pour les mariages de prestige avec cérémonies au coucher du soleil.', 'Algiers', 'Station Balnéaire de Sidi Fredj, Staoueli, Alger', 'Wedding Hall', 900, 400000, 50000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'La Rose des Sables', 'Au cœur du M''zab, La Rose des Sables offre une expérience saharienne unique pour 300 convives. Architecture mozabite traditionnelle avec tentes caïdales, éclairage aux flambeaux et ciel étoilé du désert. Cuisine du sud avec tajines, rôtis et dattes fraîches de la région. Transport en 4x4 et spectacle folklorique inclus. Magie garantie.', 'Ghardaia', 'Palmeraie de Beni Isguen, Ghardaia', 'Wedding Hall', 300, 180000, 23000, true);

-- Insert Conference Room venues (8)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Business Center El Aurassi', 'Le Business Center El Aurassi domine Alger depuis les hauteurs de l''hôtel iconique. Cette salle de conférence de 200 places offre équipements audiovisuels dernier cri, connexion fibre optique et service de traduction simultanée. Vue panoramique sur la baie d''Alger et le port. Pauses café gastronomiques et déjeuners d''affaires sur commande. Parking VIP souterrain.', 'Algiers', 'Avenue Franz Fanon, Hôtel El Aurassi, Alger', 'Conference Room', 200, 150000, 20000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Centre d''Affaires Sheraton', 'Le Centre d''Affaires du Sheraton Oran propose 150 places dans un environnement corporate international. Équipements visioconférence Cisco, écrans LED géants et mobilier ergonomique haut de gamme. Accès direct au lobby de l''hôtel 5 étoiles. Service secrétariat, reprographie et restauration disponibles 24h/24. Idéal pour séminaires et formations.', 'Oran', 'Boulevard de la Résistance, Sheraton Oran, Oran', 'Conference Room', 150, 120000, 16000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Hilton Conference Hall', 'Le Hilton Conference Hall d''Alger redéfinit les standards des événements professionnels. Capacité modulable jusqu''à 300 personnes avec cloisons acoustiques mobiles. Technologie de présentation immersive, système de vote électronique et streaming en direct. Restaurant gastronomique sur place. Service conciergerie et coordination événementielle inclus.', 'Algiers', 'Pins Maritimes, El Mohammadia, Alger', 'Conference Room', 300, 200000, 25000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'CIC Constantine', 'Le Centre International de Conférences de Constantine accueille 180 professionnels dans un cadre moderne. Situé près de l''université, il offre amphithéâtre équipé, salles de sous-commission et espace networking. Connexion haut débit, tableaux interactifs et cabines de traduction. Parking gratuit et accès handicapés. Tarifs préférentiels pour institutions.', 'Constantine', 'Campus Universitaire, Nouvelle Ville Ali Mendjeli, Constantine', 'Conference Room', 180, 100000, 13000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Salle Panoramique', 'La Salle Panoramique d''Annaba offre une vue imprenable sur le golfe pour vos réunions de 120 personnes. Baies vitrées du sol au plafond, climatisation silencieuse et acoustique optimisée. Équipements Apple TV, système Bose et tableau blanc digital. Terrasse privative pour pauses café avec vue mer. Restauration méditerranéenne légère disponible.', 'Annaba', 'Front de Mer, Cours de la Révolution, Annaba', 'Conference Room', 120, 80000, 10000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Forum Business Center', 'Le Forum Business Center de Sétif propose un espace professionnel de 100 places au cœur de la ville. Design contemporain, mobilier modulable et éclairage naturel abondant. WiFi ultra-rapide, vidéoprojecteur 4K et système de conférence téléphonique. Café et viennoiseries offerts. Localisation centrale près de la gare et des hôtels.', 'Setif', 'Centre Commercial Park Mall, Setif', 'Conference Room', 100, 70000, 9000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Le Méridien Meeting Room', 'Le Méridien Meeting Room offre intimité et luxe pour 80 participants. Décoration épurée, fauteuils en cuir et table de conférence ovale en bois noble. Service majordome dédié, pause gastronomique et espace détente adjacent. Idéal pour conseils d''administration et négociations confidentielles. Discrétion et excellence garanties.', 'Algiers', 'Rue Didouche Mourad, Centre Alger', 'Conference Room', 80, 60000, 8000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Centre El Marsa', 'Le Centre El Marsa à Sidi Fredj combine business et détente balnéaire. Salle de 250 places avec vue sur la marina et terrasse extérieure. Équipements modernes, restauration variée et activités team-building nautiques possibles. Parfait pour séminaires résidentiels avec hébergement sur place. Navette aéroport disponible.', 'Algiers', 'Port de Plaisance, Sidi Fredj, Alger', 'Conference Room', 250, 180000, 22000, true);

-- Insert Restaurant & Café venues (8)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Restaurant La Casbah', 'Le Restaurant La Casbah vous invite à privatiser un palais ottoman authentique dans la médina d''Alger. Capacité de 150 couverts répartis sur trois niveaux avec patios intérieurs et terrasse panoramique. Cuisine traditionnelle algéroise : chorba, bourek, couscous royal et pâtisseries maison. Musique chaâbi live sur demande. Expérience culturelle immersive garantie.', 'Algiers', 'Rue Sidi Driss Hamidouche, La Casbah, Alger', 'Restaurant & Café', 150, 180000, 23000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Café Glacier le Titanic', 'Le légendaire Café Glacier le Titanic d''Oran, institution depuis 1930, peut être privatisé pour 80 invités. Décor Art Déco préservé avec boiseries, vitraux et terrasse face au théâtre. Pâtisserie fine, glaces artisanales et thés orientaux. Idéal pour événements élégants, anniversaires et réceptions intimes dans un cadre historique unique.', 'Oran', 'Place du 1er Novembre, Front de Mer, Oran', 'Restaurant & Café', 80, 90000, 12000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Le Moulin d''Or', 'Le Moulin d''Or de Constantine, ancien moulin à huile transformé, accueille 120 convives dans un écrin de pierres anciennes. Cuisine fusion algéro-française avec produits locaux : agneau des Aurès, fromages de montagne et vins de Médéa. Cave voûtée pour dégustation et espace lounge avec cheminée. Parking privé sécurisé.', 'Constantine', 'Rue Abane Ramdane, Vieille Ville, Constantine', 'Restaurant & Café', 120, 130000, 17000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'La Terrasse du Port', 'La Terrasse du Port à Béjaïa offre une vue spectaculaire sur la baie pour 100 invités. Restaurant de fruits de mer avec produits pêchés quotidiennement. Grande terrasse couverte, ambiance maritime décontractée et couchers de soleil mémorables. Menu dégustation avec langouste, daurade royale et desserts aux figues. Accès direct à la plage.', 'Bejaia', 'Port de Béjaïa, Boulevard Front de Mer, Béjaïa', 'Restaurant & Café', 100, 110000, 14000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Restaurant El Djazair', 'Le Restaurant El Djazair, au sein de l''hôtel historique éponyme, reçoit 200 convives dans les anciens jardins du palais d''été. Cuisine gastronomique algérienne modernisée par un chef étoilé. Salons privés avec vue sur la mer, jardins centenaires et fontaines mauresque. Service impeccable style palace. Événements VIP et réceptions officielles.', 'Algiers', 'Hôtel El Djazair, 24 Rue Ahmed Kara, Alger', 'Restaurant & Café', 200, 220000, 28000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Café Majestic', 'Le Café Majestic incarne l''élégance algéroise depuis 1920. Privatisez ce salon de thé historique pour 60 personnes dans un décor Belle Époque intact. Mobilier d''époque, portraits anciens et service en porcelaine fine. Afternoon tea avec msemen, makroud et thé à la menthe. Parfait pour lancements littéraires et événements culturels raffinés.', 'Algiers', 'Rue Larbi Ben M''hidi, Alger Centre', 'Restaurant & Café', 60, 70000, 9000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'La Table du Pêcheur', 'La Table du Pêcheur à Annaba célèbre la Méditerranée pour 90 convives. Restaurant familial en bord de mer avec terrasse ombragée par des bougainvilliers. Spécialités : bouillabaisse annabaise, crevettes géantes grillées et vin local. Ambiance chaleureuse et authentique. Possibilité de feu de camp nocturne sur la plage privée.', 'Annaba', 'Plage Rizzi Amor, La Caroube, Annaba', 'Restaurant & Café', 90, 100000, 13000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Restaurant Tassili', 'Le Restaurant Tassili au cœur du Sahara offre une expérience culinaire unique pour 70 personnes. Architecture mozabite traditionnelle avec toit en dôme et ventilation naturelle. Cuisine du désert : méchoui, couscous aux dattes et thé touareg. Dîners sous les étoiles dans le jardin de palmiers. Spectacles de musique gnawa sur demande.', 'Ghardaia', 'Ksar de Beni Isguen, Ghardaia', 'Restaurant & Café', 70, 80000, 10000, true);

-- Insert Outdoor Garden venues (7)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Jardin Botanique', 'Le Jardin Botanique d''Alger, fondé en 1832, ouvre ses portes pour des événements exclusifs de 400 personnes. Collection unique de plantes méditerranéennes, allées ombragées par des ficus centenaires et kiosque historique. Éclairage féérique nocturne disponible. Idéal pour mariages champêtres, garden parties et événements corporate au vert dans la capitale.', 'Algiers', 'Rue Mohamed Belouizdad, El Hamma, Alger', 'Outdoor Garden', 400, 250000, 32000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Parc des Oliviers', 'Le Parc des Oliviers de Tlemcen étend ses 5 hectares d''oliveraies millénaires pour 300 invités. Cadre bucolique avec vue sur les montagnes, terrasses en pierre naturelle et fontaines traditionnelles. Restauration champêtre avec produits du terroir local. Cérémonies en plein air mémorables au coucher du soleil.', 'Tlemcen', 'Route d''El Ourit, Mansourah, Tlemcen', 'Outdoor Garden', 300, 180000, 23000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Les Vergers de Mitidja', 'Les Vergers de Mitidja à Blida accueillent 500 personnes au milieu des orangers en fleurs. Domaine agricole familial avec mas provençal, étangs et roseraie. Tentes caïdales ou réception sous les étoiles. Cuisine fermière avec légumes du potager et agrumes fraîchement cueillis. Activités : promenade en calèche et cueillette saisonnière.', 'Blida', 'Route de Chréa, Montagne de Blida', 'Outdoor Garden', 500, 300000, 38000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Domaine El Nakhla', 'Le Domaine El Nakhla à Biskra offre l''oasis parfaite pour 350 convives. Palmeraie ancestrale avec bassins d''irrigation traditionnels, pergolas naturelles et tentes sahariennes. Températures clémentes en soirée, ciel étoilé exceptionnel. Cuisine du sud avec couscous aux dattes et méchoui cuit au feu de bois. Dépaysement total garanti.', 'Biskra', 'Palmeraie de Tolga, Route de Touggourt, Biskra', 'Outdoor Garden', 350, 200000, 25000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Jardin des Zianides', 'Le Jardin des Zianides de Tlemcen, ancien jardin royal, peut accueillir 250 invités dans un décor historique andalou. Bassins, jets d''eau et cyprès sculptés créent une atmosphère envoûtante. Accès au site archéologique de Mansourah. Musique andalouse traditionnelle et restauration mauresque disponibles. Événements culturels et mariages de prestige.', 'Tlemcen', 'Mansourah, Site Archéologique, Tlemcen', 'Outdoor Garden', 250, 160000, 20000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Parc El Hamma', 'Le Parc El Hamma, plus ancien jardin d''Afrique, offre 600 places dans un écrin de verdure exotique. Bambouseraie, jardins français et anglais, serres tropicales et lac artificiel. Éclairage architectural nocturne spectaculaire. Possibilité de croisière en barque et promenade en petit train. Événements de prestige dans un lieu historique classé.', 'Algiers', 'Boulevard Mohamed Belouizdad, El Hamma, Alger', 'Outdoor Garden', 600, 350000, 45000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Les Jardins Andalous', 'Les Jardins Andalous d''Oran recréent le paradis mauresque pour 400 personnes. Fontaines chantantes, mosaïques zellige et orangers en fleurs composent ce décor de rêve. Pavillon central pour réceptions, allées romantiques et éclairage aux bougies. Gastronomie oranaise raffinée et musique raï acoustique sur demande.', 'Oran', 'Plateau Saint-Michel, Hai Sidi El Houari, Oran', 'Outdoor Garden', 400, 280000, 35000, true);

-- Insert Hotel & Resort venues (8)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Sofitel Algiers', 'Le Sofitel Algiers Hamma Garden propose ses salons de réception pour 500 invités dans un cadre 5 étoiles luxe. Ballroom avec plafonds de 6 mètres, lustres monumentaux et service traiteur gastronomique français. Chambres pour invités, spa et piscine disponibles. Coordination événementielle dédiée et attention aux moindres détails.', 'Algiers', 'Hamma Garden, 172 Rue Hassiba Ben Bouali, Alger', 'Hotel & Resort', 500, 450000, 55000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Sheraton Oran', 'Le Sheraton Oran offre 400 places dans ses salles modulables face à la Méditerranée. Standard international Starwood avec équipements audiovisuels premium. Terrasse extérieure avec vue mer pour cocktails. Service personnalisé, hébergement sur place et transfer aéroport. Mariages et galas d''exception.', 'Oran', 'Boulevard de la Résistance, Oran', 'Hotel & Resort', 400, 380000, 48000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'AZ Hotel Zeralda', 'L''AZ Hotel Zeralda combine plage et luxe pour 350 invités. Resort balnéaire 4 étoiles avec salle de banquet vue mer, jardins tropicaux et piscine olympique. Activités nautiques, beach party et feux de camp possibles. Cuisine internationale et locale. Séminaires résidentiels et mariages en bord de mer.', 'Algiers', 'Zone Touristique de Zeralda, Alger Ouest', 'Hotel & Resort', 350, 300000, 38000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Marriott Constantine', 'Le Marriott Constantine propose 300 places dans un environnement corporate haut de gamme. Situation centrale, technologie de pointe et service Marriott impeccable. Ballroom divisible, salons privés et restaurant panoramique. Idéal pour conférences internationales et événements d''entreprise dans l''est algérien.', 'Constantine', 'Nouvelle Ville Ali Mendjeli, Constantine', 'Hotel & Resort', 300, 280000, 35000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Royal Tulip', 'Le Royal Tulip d''Alger incarne le luxe absolu pour 600 invités. Ballroom de 1200m² avec lustre central de 3 tonnes, revêtements en marbre italien et système son Bose. Suites présidentielles, spa Guerlain et restaurants étoilés. Service de wedding planner intégré et attention aux moindres détails.', 'Algiers', 'Pins Maritimes, El Mohammadia, Alger', 'Hotel & Resort', 600, 500000, 62000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Ibis Styles Setif', 'L''Ibis Styles Setif propose une option moderne et abordable pour 150 invités. Design contemporain coloré, équipements multimédia et restauration quality. Localisation centrale près du centre commercial. Parfait pour séminaires d''entreprise et réceptions de taille moyenne dans les Hauts Plateaux.', 'Setif', 'Centre Commercial Park Mall, Setif', 'Hotel & Resort', 150, 180000, 23000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Four Points Oran', 'Le Four Points by Sheraton Oran accueille 250 personnes avec vue sur le port. Standard international, salles modulables et terrasse panoramique. Service traiteur varié, bar lounge et chambres confortables. Coordination événementielle professionnelle. Mariages élégants et conférences dans l''ouest algérien.', 'Oran', 'Les Andalouses, Route de Mers El Kébir, Oran', 'Hotel & Resort', 250, 250000, 32000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Oasis Beach Resort', 'L''Oasis Beach Resort de Tipaza offre 400 places entre ruines romaines et plage dorée. Complexe balnéaire 4 étoiles avec bungalows, piscines et jardins méditerranéens. Buffets en plein air, soirées plage et vue sur Chenoua. Destination idéale pour mariages romantiques et team-buildings mémorables.', 'Tipaza', 'Zone Touristique de Tipaza, Route de Cherchell', 'Hotel & Resort', 400, 350000, 44000, true);

-- Insert Private Villa venues (8)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Villa El Biar', 'La Villa El Biar, demeure coloniale des années 1920, accueille 100 invités dans le quartier résidentiel le plus prisé d''Alger. Jardins à la française, terrasse panoramique sur la baie et salons avec boiseries d''époque. Intimité totale et service personnalisé. Idéale pour réceptions privées, shootings photos et événements exclusifs.', 'Algiers', 'Rue des Frères Mesli, El Biar, Alger', 'Private Villa', 100, 200000, 25000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Villa Canastel', 'La Villa Canastel d''Oran surplombe la Méditerranée pour 80 invités. Architecture mauresque blanche avec piscine à débordement, vue mer 180° et jardins méditerranéens. Ambiance côte d''Azur avec charme oriental. Parfaite pour anniversaires intimes, fiançailles et petits mariages de luxe.', 'Oran', 'Canastel, Route de la Corniche, Oran', 'Private Villa', 80, 150000, 19000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Dar El Kenz', 'Dar El Kenz à Constantine incarne le patrimoine constantinois pour 120 personnes. Palais ottoman restauré avec cours intérieure, fontaines et moucharabiehs sculptés. Surplombe les gorges du Rhumel avec vue spectaculaire. Cuisine traditionnelle de l''est et musique malouf. Événements culturels et mariages authentiques.', 'Constantine', 'Rue Didouche Mourad, Souika, Constantine', 'Private Villa', 120, 180000, 23000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Villa des Roses', 'La Villa des Roses en Kabylie accueille 60 invités dans un havre de paix montagnard. Chalet kabyle moderne avec terrasse sur le Djurdjura, jardin fleuri et barbecue. Ambiance familiale et chaleureuse. Possibilité d''hébergement dans les dépendances. Anniversaires, réunions familiales et petites célébrations.', 'Tizi Ouzou', 'Ait Ouabane, Route de Tikjda, Tizi Ouzou', 'Private Villa', 60, 120000, 15000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Résidence Sidi Fredj', 'La Résidence Sidi Fredj propose 150 places dans un domaine privé face à la mer. Villa principale et dépendances avec accès plage privée, piscine et tennis. Idéale pour mariages de prestige avec hébergement des invités. Service traiteur haut de gamme et coordination événementielle complète.', 'Algiers', 'Lotissement Front de Mer, Sidi Fredj, Alger', 'Private Villa', 150, 280000, 35000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Villa Panoramique', 'La Villa Panoramique d''Annaba offre une vue à 360° sur la ville et la mer pour 90 invités. Architecture contemporaine avec grandes baies vitrées, terrasse sur le toit et piscine. Design minimaliste élégant. Parfaite pour lancements produits, events corporate et célébrations modernes.', 'Annaba', 'Seraïdi, Montagne des Oliviers, Annaba', 'Private Villa', 90, 160000, 20000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Maison El Harrach', 'La Maison El Harrach, villa art déco des années 30, accueille 70 personnes dans un jardin luxuriant. Hauts plafonds, parquets d''origine et véranda. Quartier calme proche du centre d''Alger. Atmosphère bohème chic pour réceptions artistiques, anniversaires et événements culturels.', 'Algiers', 'El Harrach, Commune de Bourouba, Alger', 'Private Villa', 70, 130000, 17000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Villa Turquoise', 'La Villa Turquoise de Tipaza combine vestiges romains et confort moderne pour 100 invités. Propriété en bord de mer avec jardin archéologique privé, piscine et terrasse sunset. Vue sur le parc de Tipaza. Mariages romantiques avec cérémonie au coucher du soleil face aux colonnes antiques.', 'Tipaza', 'Route du Littoral, Chenoua Plage, Tipaza', 'Private Villa', 100, 220000, 28000, true);

-- Insert Rooftop & Terrace venues (7)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Sky Lounge Alger', 'Le Sky Lounge Alger, au 18ème étage d''une tour emblématique, accueille 150 invités avec vue 360° sur la capitale. Design contemporain, bar panoramique et piste de danse sous les étoiles. DJ resident et cocktails signature. Soirées VIP, lancements et événements corporate spectaculaires.', 'Algiers', 'Tour Business Center, Bab Ezzouar, Alger', 'Rooftop & Terrace', 150, 200000, 25000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Le Panorama', 'Le Panorama d''Oran offre 100 places sur les toits de la ville avec vue sur Santa Cruz et le port. Terrasse élégante avec mobilier lounge, éclairage d''ambiance et bar cocktails. Cuisine fusion méditerranéenne. Couchers de soleil mémorables et ambiance festive oranaise garantie.', 'Oran', 'Front de Mer, Immeuble Les Terrasses, Oran', 'Rooftop & Terrace', 100, 150000, 19000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Terrasse du Cirta', 'La Terrasse du Cirta à Constantine surplombe les gorges du Rhumel pour 80 invités. Vue vertigineuse sur les ponts suspendus et la médina illuminée. Décor mauresque moderne avec fontaines et végétation. Gastronomie constantinoise et nuits étoilées. Expérience unique dans la ville des ponts.', 'Constantine', 'Rue Larbi Ben M''hidi, Vieille Ville, Constantine', 'Rooftop & Terrace', 80, 120000, 15000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Rooftop El Aurassi', 'Le Rooftop El Aurassi, au sommet de l''hôtel iconique, accueille 200 personnes avec vue imprenable sur la baie d''Alger. Espace extérieur et intérieur climatisé, bar premium et service 5 étoiles. Événements de prestige avec le meilleur panorama de la capitale.', 'Algiers', 'Hôtel El Aurassi, Avenue Franz Fanon, Alger', 'Rooftop & Terrace', 200, 280000, 35000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Vista Grande', 'Vista Grande à Annaba propose 120 places sur une terrasse face au golfe. Ambiance chic décontractée avec lounges confortables, parasols design et bar à tapas. Vue sur le phare et les plages de Seraïdi. Soirées blanches, anniversaires et événements corporate estivaux.', 'Annaba', 'Boulevard du 1er Novembre, Annaba Centre', 'Rooftop & Terrace', 120, 160000, 20000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Le Belvédère', 'Le Belvédère de Béjaïa offre 90 places avec vue spectaculaire sur Cap Carbon et la baie. Terrasse en bois exotique, pergolas fleuries et éclairage romantique. Spécialités de fruits de mer et vins locaux. Fiançailles, anniversaires et petits mariages avec vue mer exceptionnelle.', 'Bejaia', 'Cap Carbon, Route Touristique, Béjaïa', 'Rooftop & Terrace', 90, 140000, 18000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Sky Garden Alger', 'Le Sky Garden Alger, jardin suspendu au 12ème étage, accueille 180 invités dans un oasis urbain. Végétation luxuriante, fontaines zen et mobilier design. Vue sur la Grande Poste et le port. Événements green, lancements écoresponsables et réceptions avec conscience environnementale.', 'Algiers', 'Tour El Hamma, Boulevard Mohamed Belouizdad, Alger', 'Rooftop & Terrace', 180, 250000, 32000, true);

-- Insert Event Center venues (8)
INSERT INTO venues (host_id, name, description, city, address, category, capacity, price_per_day, price_per_hour, is_active) VALUES
('edc892af-b631-46e5-92e2-933efb65f0af', 'Palais des Expositions', 'Le Palais des Expositions d''Alger, complexe événementiel majeur, propose jusqu''à 2000 places dans ses halls modulables. Équipements professionnels pour salons, foires et congrès internationaux. Parking 1500 places, restauration collective et centre de presse. La référence nationale pour événements de grande envergure.', 'Algiers', 'Pins Maritimes, Safex, El Mohammadia, Alger', 'Event Center', 2000, 800000, 100000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Centre des Conventions', 'Le Centre des Conventions d''Oran accueille 1500 personnes pour conférences internationales et galas. Architecture moderne, amphithéâtre équipé traduction simultanée et foyer d''exposition. Situation centrale proche aéroport et hôtels. Événements institutionnels et corporate de prestige dans l''ouest.', 'Oran', 'Boulevard de l''ALN, Oran Centre', 'Event Center', 1500, 600000, 75000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Salle Ibn Khaldoun', 'La Salle Ibn Khaldoun d''Alger, mythique salle de spectacles, peut être privatisée pour 800 invités. Acoustique exceptionnelle, scène professionnelle et équipements concert. Idéale pour galas, remises de prix, concerts privés et cérémonies officielles. Patrimoine culturel algérien incontournable.', 'Algiers', 'Rue Didouche Mourad, Alger Centre', 'Event Center', 800, 400000, 50000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'CCI Constantine', 'Le Centre de la Chambre de Commerce de Constantine propose 600 places pour séminaires et expositions régionales. Amphithéâtre, salles de réunion et espace networking. Équipements modernes et tarifs compétitifs. Conférences professionnelles et salons thématiques dans l''est algérien.', 'Constantine', 'Avenue Aouati Mostefa, Constantine Centre', 'Event Center', 600, 300000, 38000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Complexe Culturel', 'Le Complexe Culturel de Sétif offre 500 places dans un bâtiment multifonctionnel moderne. Théâtre, galerie d''exposition et salles de conférence. Idéal pour festivals, événements culturels et congrès régionaux. Partenariats avec institutions éducatives et culturelles.', 'Setif', 'Rue 8 Mai 1945, Centre-Ville, Setif', 'Event Center', 500, 250000, 32000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Maison de la Culture', 'La Maison de la Culture Mouloud Mammeri de Tizi Ouzou accueille 400 personnes pour événements culturels. Auditorium, bibliothèque et espaces polyvalents. Architecture kabyle contemporaine et vue sur les montagnes. Spectacles, conférences et événements communautaires.', 'Tizi Ouzou', 'Boulevard Stiti Ali, Nouvelle Ville, Tizi Ouzou', 'Event Center', 400, 200000, 25000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Salle Omnisports', 'La Salle Omnisports de Blida, reconvertible en espace événementiel, accueille 1000 personnes. Plancher amovible, gradins rétractables et éclairage spectacle. Concerts, galas sportifs et grands rassemblements dans la région de la Mitidja.', 'Blida', 'Cité Olympique, Route de Chréa, Blida', 'Event Center', 1000, 450000, 56000, true),
('edc892af-b631-46e5-92e2-933efb65f0af', 'Centre des Arts', 'Le Centre des Arts d''Annaba propose 350 places dans un espace polyvalent moderne. Galeries, ateliers et salle de spectacles. Vue sur la mer depuis la terrasse. Expositions, vernissages, concerts acoustiques et événements culturels dans l''est algérien.', 'Annaba', 'Boulevard de la Révolution, Front de Mer, Annaba', 'Event Center', 350, 180000, 23000, true);