// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kctouaomtfepccaohhxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjdG91YW9tdGZlcGNjYW9oaHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Njk3NjksImV4cCI6MjA2NTE0NTc2OX0.drumw_GAeLTUHcKJXKa4NU5pWWUSdFmpJ29-nk40Bsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);